### ISSUE TITLE
关于Global Pointer问题

### ISSUE THREAD

**Issue by GeneKong** [kendryte/kendryte-freertos-sdk#1]
RISC V的全局指针在linker里面是一个**特殊的字符**，应该为__global_pointer$，这个是linker决定的，目前linker脚本给的是_gp，此指针主要用于优化全局变量的操作；
这里crt.S
```S
  la gp, _gp
```
和kendryte.ld
```
  .data :
  {
    /* Writable data segment (.data segment) */
    *(.data .data.*)
    *(.gnu.linkonce.d.*)
    /* Have _gp point to middle of sdata/sbss to maximize displacement range */
    . = ALIGN(8);
    PROVIDE( _gp = ABSOLUTE(.) + 0x800);
```
可以同步下.

**Comment by sunnycase** [comment]
RV 官方工具链确实已将 _gp 更新为 _global_pointer$。https://github.com/riscv/riscv-binutils-gdb/pull/56

**Comment by manageryzy** [comment]
![8](https://user-images.githubusercontent.com/6567674/45730175-ddaf2680-bc02-11e8-846c-c1d1283a5131.jpg)

**Comment by ly0** [comment]
The issue is closed since #2 fixed this.
