### ISSUE TITLE
ubuntu 18.04 crosstoolchain linkerr in  libmpfr.so.4

### ISSUE THREAD

**Issue by chentyjpm** [kendryte/kendryte-freertos-sdk#19]
Make sure you read and understand this document.
Use one of the two templates below and delete the rest.

- [x] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

When use ubuntu 18.04 toolchain miss libmpfr.so.4 cause compile err in SDK

-- Configuring done
-- Generating done
-- Build files have been written to: /data/k210/kendryte-freertos-sdk-0.2.0/build
[  1%] Building C object SDK/CMakeFiles/kendryte.dir/bsp/config/fpioa_cfg.c.obj
/opt/riscv-toolchain/bin/../libexec/gcc/riscv64-unknown-elf/7.2.0/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
SDK/CMakeFiles/kendryte.dir/build.make:62: recipe for target 'SDK/CMakeFiles/kendryte.dir/bsp/config/fpioa_cfg.c.obj' failed
make[2]: *** [SDK/CMakeFiles/kendryte.dir/bsp/config/fpioa_cfg.c.obj] Error 1
CMakeFiles/Makefile2:122: recipe for target 'SDK/CMakeFiles/kendryte.dir/all' failed
make[1]: *** [SDK/CMakeFiles/kendryte.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

when add env of LD_LIBRARY it  fixed

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/riscv-toolchain/bin
server@server-AI:/opt/riscv-toolchain/bin$ cd /data/k210/kendryte-freertos-sdk-0.2.0/build/
server@server-AI:/data/k210/kendryte-freertos-sdk-0.2.0/build$ cmake .. -DPROJ=hello_world -DTOOLCHAIN=/opt/riscv-toolchain/bin && make

[ 92%] Building C object SDK/CMakeFiles/kendryte.dir/bsp/crt.S.obj
[ 94%] Building C object SDK/CMakeFiles/kendryte.dir/freertos/portable/portasm.S.obj
[ 96%] Linking C static library libkendryte.a
[ 96%] Built target kendryte
Scanning dependencies of target hello_world
[ 98%] Building C object CMakeFiles/hello_world.dir/src/hello_world/main.c.obj
[100%] Linking C executable hello_world
Generating .bin file ...
[100%] Built target hello_world

**Comment by sunnycase** [comment]
You can create a symobol that link libmpfr.so.6 to libmpfr.so.4.

**Comment by sunnycase** [comment]
Closed for no response. Feel free to reopen if you have any question.

**Comment by chentyjpm** [comment]
thanks
