### ISSUE TITLE
can not compile, missing encoding.h

### ISSUE THREAD

**Issue by 0x00-pl** [kendryte/kendryte-freertos-sdk#24]
Make sure you read and understand this document.
Use one of the two templates below and delete the rest.

- [ *] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Actual behavior

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pl/Downloads/tmp/freertos-test/build
Scanning dependencies of target drivers
[  2%] Building C object lib/drivers/CMakeFiles/drivers.dir/clint.c.obj
/home/pl/Downloads/tmp/kendryte-freertos-sdk/lib/drivers/clint.c:15:10: fatal error: encoding.h: No such file or directory
 #include <encoding.h>
          ^~~~~~~~~~~~
compilation terminated.

### Test code

Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

```bash
# Add code here
```

### Document version

Which branch are you on? If you know the Git revision then add it here as well.

### Hardware

Which hardware do you use?

### System

What system do you use?

-------------------------------------------------------------------------------
> FEATURE REQUEST

### Justification

Tell us why you would like to see this feature added.

### Workarounds

Are there any workarounds you currently have in place because the feature is missing?

**Comment by sunnycase** [comment]
I can't reproduce the problem. Can you give more information?

**Comment by 0x00-pl** [comment]
my CMakeLists.txt is miss match
close
