### ISSUE TITLE
Build bin file issue

### ISSUE THREAD

**Issue by Moo2017** [kendryte/kendryte-freertos-sdk#35]
Make sure you read and understand this document.
Use one of the two templates below and delete the rest.

- [ ] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Test code

Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

```bash
# Add code here
```

### Document version

Which branch are you on? If you know the Git revision then add it here as well.

### Hardware

Which hardware do you use?

### System

What system do you use?

-------------------------------------------------------------------------------
> FEATURE REQUEST

### Justification

Tell us why you would like to see this feature added.

### Workarounds

Are there any workarounds you currently have in place because the feature is missing?

**Comment by Moo2017** [comment]
I downloaded kendryte-freertos-sdk and also installed cmake and  Visual C++ Build Tools. IOnce I run the make command I am getting the following error and .bin file doesn't apear:
![image](https://user-images.githubusercontent.com/34062463/52089433-85a70a00-257c-11e9-9ac2-7efaf420fcdd.png)

**Comment by sunnycase** [comment]
Use `mingw32-make` on Windows.
