### ISSUE TITLE
lvgl macro and sub directory support

### ISSUE THREAD

**Issue by Moo2017** [kendryte/kendryte-freertos-sdk#36]
Hi All, I am trying to add lvgl to the lcd project but it gives me some errors (#include ../../lv_conf.h No such file or directory) , I should mention that it is ok with kendryte-standalone-sdk. Also I have issue adding sub folder and libraries into the project in general.

**Comment by Masi2017** [comment]
Hi All, I am trying to add lvgl to the lcd project but it gives me some errors (#include ../../lv_conf.h No such file or directory) , I should mention that it is ok with kendryte-standalone-sdk.

**Comment by sunnycase** [comment]
You can add a project specific cmake, see https://github.com/kendryte/kendryte-freertos-demo/blob/master/tflite_label_image/project.cmake for reference.
