### ISSUE TITLE
FreeRTOS port up to date

### ISSUE THREAD

**Issue by baldhead69** [kendryte/kendryte-freertos-sdk#69]
Why freeRTOS are not supported anymore ?

I want to use a rtos on k210.
And possibly for product development.

What rtos are supported by kendryte k210 now ?

"[warning]This project is no longer maintained.Not recommended for product development."

**Comment by z3cko** [comment]
Hey baldhead69, i am working on a port currently. Please get in contact with me via github if you want to join forces.

**Comment by baldhead69** [comment]
Hi @z3cko,

if i know how to help i can help yes.

and it would also be a good learning experience for me.

**Comment by z3cko** [comment]
Please contact me at embedded@sani.ai - i seem to not be able to write you via github

**Comment by baldhead69** [comment]
I send email to you with um hi, and the answer was this:

Hello rangel@.......

We're writing to let you know that the group you tried to contact (embedded) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/sani.ai/bin/topic.py?topic=25838.

Thanks,

sani.ai admins

**Comment by c4esp** [comment]
Hello @baldhead69 @z3cko 

Do you find a solution about that...maybe it is the same problem that I opened in the issue:
https://github.com/kendryte/kendryte-freertos-sdk/issues/71

Thanks in advance.

Jose.

**Comment by baldhead69** [comment]
@c4esp 

No solution. I think that k210 dont have support to freertos or another rtos yet.

**Comment by c4esp** [comment]
Hi,

What are you refering when you talk about k210 do not support FreeRTOS?

FreeRTOS is supported and this example with detect.kmodel works awesome.

https://github.com/kendryte/kendryte-freertos-demo/tree/develop/face_detect

Thanks in advance.

Jose.

**Comment by baldhead69** [comment]
https://github.com/kendryte/kendryte-freertos-sdk

[warning]This project is no longer maintained.Not recommended for product development.

**Comment by c4esp** [comment]
OMG!!! If that is true I do not understand how they set a big warning in README FILE!!!

In any case, do you know how they generate the kmodel file from face_detect example

https://github.com/kendryte/kendryte-freertos-demo/tree/develop/face_detect

Thanks in advance @baldhead69

**Comment by baldhead69** [comment]
I dont understand nothing of ia.

**Comment by baldhead69** [comment]
kendryte abandoned its customers
